### ISSUE TITLE
Add "Premium data" funnels into datahub-kpis dataset

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datahub-kpis#11]
## Acceptance criteria

* [x] I have a resource "premium-data-funnel-daily" and "premium-data-funnel-weekly"
* [x] I have graphs that visualise funnels so I can better understand trends/situation

## Tasks

* [x] generate weekly data using daily data
* [x] add both resources into "datahub-kpis" dataset
* [x] add graphs

**Comment by anuveyatsu** [comment]
FIXED - see the last graph in https://datahub.io/examples/datahub-kpis - there is not enough data for now but the line on the graph will appear once enough data is collected.
