### ISSUE TITLE
Align KPIs with the new homepage and offers pages

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datahub-kpis#12]
*Estimate is unknown at the moment, as we don't know what impact new implementation will have on the analytics/kpis.*

## Acceptance criteria

* [x] after deployment of the new design of homepage and offers pages, the KPIs are still tracked in the same way and works great

## Tasks

* [x] analysis and verification if KPIs tracking works well
* [ ] ~~fix if anything is broken~~

**Comment by anuveyatsu** [comment]
CHECKED https://datahub.io/datahq/datahub-kpis dataset and it works fine without modifications.
