### ISSUE TITLE
Run regularly / extract 7 day windows from the past

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datahub-kpis#5]
## Acceptance criteria

* [x] the script is run on weekly basis

## Tasks

* [x] convert script into simple Python file `funnel.py`
* [x] run the `funnel.py` once a week using Travis

**Comment by anuveyatsu** [comment]
FIXED but we've decided to run script on daily basis
