### ISSUE TITLE
Create a dataset from historical data

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datahub-kpis#7]
## Acceptance criteria

* [x] a dataset `datahub-kpis` published under some special user, eg, `examples` user
* [x] the dataset is auto-pushed when data in this repo is updated
* [x] the dataset has graphs that shows insights about KPIs

## Tasks

* [x] Fetch historical data starting from 1st January 2018 from GA
  * [x] Implement a script for getting daily data
  * [x] Implement a script for converting daily to weekly data
  * [x] Check data is good enough
* [x] generate `datapackage.json` using init command
* [x] validate the dataset - fix schema if needed
* [x] add views using weekly/daily data
* [x] setup Travis to push the dataset on regular basis (when it pulls new data from google analytics)
* [x] get a review from Adam
* [x] final touch

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/examples/datahub-kpis or https://datahub.io/datahq/datahub-kpis
