### ISSUE TITLE
Define "Premium data" funnel

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datahub-kpis#8]
As we're putting "Premium data" offer on showcase page, we want to track how many users interested in such an offer + we want some KPIs so we can improve (e.g., we do some changes and see how it affects KPIs).

## Acceptance criteria

* [x] List of funnels with name, description and info about how it is defined in the GA

## Tasks

* [x] List funnel item names (use one written by Adam in sprint plan)
* [x] Add description
* [x] Check how it is defined in the GA or if needs an implementation
* [x] get review from Adam
* [x] finish up

**Comment by anuveyatsu** [comment]
**Use total users but not new users because we want to track all users including old ones:**

1. Incoming User
  * users that visited showcase page (only core datasets)
    * the funnel would look like: `('Incoming User', path('/core/[^/]+'), 'count')`
2. Interacting User
  * this can be considered in 2 steps:
    * user that scrolls down the page
    * user that downloads resources or copies embeddables
3. Interested User
  * users that clicked on links in the banner about "Premium data" offer and saw the modal
    * implement better tracking, e.g., check the links by class name and add a special label for GA
4. Engaged User
  * users that filled the form
    * funnel: `('Engaged User', path('https://datahub.io/premium-data?done=1'), 'count')`
5. Hooked User
  * users that signed up for "Premium data" offer
    * I suggest we fill this manually

**Comment by anuveyatsu** [comment]
FIXED - we implement funnels in https://github.com/datahq/datahub-kpis/issues/10
