### ISSUE TITLE
Track users that clicked on links in the banner about "Premium data" offer

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datahub-kpis#9]
We need it to be able to track "Interested users".

## Acceptance criteria

* [x] I can see the count of clicks on the links in the banner using GA dashboard

## Tasks

* [x] add a class to the links, e.g., "premium-offer"
* [x] create a trigger in the tags manager which triggers on showcase page when link has the class
* [x] track it as an event with category "showcase", action "click", label "premium-offer"

**Comment by anuveyatsu** [comment]
FIXED
